### ISSUE TITLE
Grammar checking for beanshell

### ISSUE THREAD

**Issue by garychow97** [lispercat/sailpoint-iiq-dev-accelerator#11]
Hi,

Appreciate for the Dev accelerator. Helps a lot on the IIQ development.

Is there any grammar checking or auto-correct of class name of the beanshell in XML? Can I refer to the IdentityIQ.jar when using this extension?

Thanks

**Comment by lispercat** [comment]
yes, language server and intelli-sense is on my to do list, just need to
find the time!

**Comment by garychow97** [comment]
Hi,

I saw it marked as closed.

Is the language server and intellisense ready now?

I am looking forward to this improvement!!

**Comment by lispercat** [comment]
Sorry for that, but I am just trying to be more realistic about the
expectations.
I did look into that, but currently the existing Java language server
doesn't support easy integration with embedded java.
We do have some basic syntax checking if you check the "Enable LSP" box in
the iiq configuration in VSCode (I'll need to see if it's still working as
some people were working on that piece).
Also I asked around, some people myself included write their code in Java
environment and then paste it to the rules when the code gets complicated
enough, so that gives them all the right IntelliSense features.
Yeah, the language server is on my mind. I may look into that when I have
cycles or someone proposes a PR for that ;)
