### ISSUE TITLE
Support for lightweight version of VS Code running fully in the browser (https://vscode.dev/)

### ISSUE THREAD

**Issue by nbhansali** [lispercat/sailpoint-iiq-dev-accelerator#17]
Hey! Love the tool and continue to leverage it. Wanted to submit a feature request to have support for https://vscode.dev/

**Comment by nbhansali** [comment]
All good, let me know if I can assist in any manner! :)

**Comment by lispercat** [comment]
Sorry for the long delay. 
We only use the VSCode for on-prem or on the same computer VM projects.
My understanding is that making the extension Web capable the Sailpoint IIQ has to be in the cloud or your configuration needs to be so that you could connect from the cloud based extension to your on-prem IIQ instance.
Not sure how would it work.
