### ISSUE TITLE
Post request failed with FetchError: request to https://MY-IIQ-URL:8443/identity/rest/workflows/IIQDevAcceleratorWF/launch failed, reason: self signed certificate

### ISSUE THREAD

**Issue by martinwoit** [lispercat/sailpoint-iiq-dev-accelerator#18]
Hey,
many thanks to the extension! 

Currently I'm trying to connect but it fails due to the self signed cert. Is there a possibility to have a setting to ignore certificate issues?

Post request failed with FetchError: request to https://MY-IIQ-URL:8443/identity/rest/workflows/IIQDevAcceleratorWF/launch failed, reason: self signed certificate 

Thank you in advance,
Martin

**Comment by martinwoit** [comment]
temp solution:

~/.vscode/extensions/andreistebakov.sailpoint-iiq-dev-accelerator-1.0.27/out/commands.js

uncomment line 336 to
`      process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0;`

Save file. Restart VSCode.

**Comment by lispercat** [comment]
Thanks, Martin, for using the plugin!
You are exactly right about your workaround.
In the code takes care of unauthorized certificates by creating this agent:
    const agent = parsedUrl.protocol === 'https:' ?  new
https.Agent({rejectUnauthorized: false}):new http.Agent();

The thing with VSCode is that it itself is in a constant flux and I had
cases when this agent stopped working with some new update and then started
working again :)
The process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0; is a little more
"drastic" solution but it works too (that's why I kept it commented out
just in case).
Let's watch this issue for some time, good that you found the fix!

**Comment by kgknox27** [comment]
Hi, 

Apologies I know this issue is closed. I had this and previously used the work around described by @martinwoit to fix this for my sandbox. However, after upgrading to the most recent version (jan 6) it is broken for me again. I went back into the file and noticed line 336 was commented out again. I uncommented and reloaded vscode but I am still getting the issue. Any ideas?

**Comment by markearnest** [comment]
Uncomment the one in andreistebakov.sailpoint-iiq-dev-accelerator-1.0.31/client/out/commands.js

**Comment by lispercat** [comment]
I used to have that issue before when I upgraded to some new version of
VSCode, but I haven't seen that issue for a while.
Guys, if you like I can create a config variable that would keep the line
of code enabled if the variable is set.
This way you won't have to modify the code with every new upgrade.

**Comment by lispercat** [comment]
I released 1.0.32 which has a config
variable iiq-dev-accelerator.disableTLSValidation. If you set it to true,
the NODE_TLS_REJECT_UNAUTHORIZED will be set to 0.
