### ISSUE TITLE
Compare with deployed translations

### ISSUE THREAD

**Issue by derekhackbardt** [lispercat/sailpoint-iiq-dev-accelerator#22]
Nice feature/change would be if the compare with deployed option could strip 'id' attributes, add CDATA tags, and undo some translation done by iiq to allow for cleaner compares.   I've come to expect &,<,'id' items to appear as differences and ignore them  but if the process could cleanup some of these it would make comparisons a little bit easier.

**Comment by lispercat** [comment]
That's a cool idea, Derek. My only concern would be when the user selects
the "Compare Local with Deployed" command, they might be a bit confused
seeing stuff that should be missing or different on the server side.
Also if you insert CDATA tags, you need to know where to insert them (same
line as <Source> or below) so that you wouldn't see a difference.
But I get your point, I like it, let me think about it and put it in the
wish list.

**Comment by lispercat** [comment]
Also I noticed that indentation for XML blocks that come back from the
server is different from your original code.
Removing ids may be beneficial in some cases, but some people may choose to
use some ids in their original source code (we do that in some cases) so
removing ids could be misleading for some.

**Comment by lispercat** [comment]
Closing as the feature has been implemented as of version 1.0.35
