### ISSUE TITLE
Refresh Object not working

### ISSUE THREAD

**Issue by robgarcav** [lispercat/sailpoint-iiq-dev-accelerator#30]
Whenever I try to refresh object from VS Code, the following message pop ups:

![image](https://user-images.githubusercontent.com/34972093/190584112-6c54ffb3-210f-4b10-8c81-9677fa227a21.png)

**Comment by lispercat** [comment]
Have you taken this object using the "Get Object" command or it's some
existing xml file on the disk?
The Refresh Object is only applicable to those objects that you obtained
from your remote server using "Get Object" command.

**Comment by robgarcav** [comment]
I get it with "Get Object".
I'm checking now that there is a problem with the name of the file... if I change the name and path when I save the XML after doing the "Get Object", then the "Refresh Object" won't work...
When I do "GetObject", the file suggests being saved on a temp location on my computer that is outside my project path, so that's why I'm moving it...

**Comment by robgarcav** [comment]
I attach a pic about where the file appears after GetObject 
![image](https://user-images.githubusercontent.com/34972093/190712137-fe6b381a-5b3d-4187-9552-53a19eeafa5d.png)

**Comment by lispercat** [comment]
Does it work if you don't save it under your project folder?
The original idea for refresh was to get an object in a temp folder and get
a refreshed (new version) from the server and compare them.
From your picture it looks like your file is in a temporary location, so it
should work properly, the only thing I can think of is that this temp
folder is part of your IIQ project folder, otherwise the error that you get
doesn't make sense to me.
Also to deal with saved object there is a "Compare Local with Deployed"
command, see if that works for you.
Yes, there is a bit of redundancy there, maybe I can combine them together
so that I disregard whether the current object is in the project or in a
temp folder.

**Comment by robgarcav** [comment]
Yes, if I save it on the temp default folder everything works fine.
The problem is that the path doesn't make any sense... my project is under "/Users/myuser/Downloads/ssb/" so I don't understand why it's going outside.
Also, I don't why it fails even if I name the object by <Class>-<objectName>.xml

**Comment by robgarcav** [comment]
Hey, have u been able to check this lately? I was wondering maybe I can give it a look and try to make the GetObject to ask for a folder to place the retrieved object place it there with "ClassName-ObjectName.xml" format.
Tell me if you have anything else in mind, so I can try to help with it.
Happy new year, by the way! :)

**Comment by lispercat** [comment]
Happy New Year, Roberto, thanks for checking in!
Please check out the latest 1.0.42 where I put a fix for "Refresh
object", see if it works for you.
